### ISSUE TITLE
Problems with Thaumcraft

### ISSUE THREAD

**Issue by Shazuli** [jaredlll08/ModTweaker#338]
Hi!
 
I've been trying to add a research to make a craftable "Crimson Blade" from Thaumcraft 5 version 5.2.4 game version 1.8.9.
 
I'm having problems adding pages to the research icon I just made. When reloading I get a unusuall Error message:
 
Error executing Thaumcraft.zs: INFUSION_ENCHANTMENT
[22:00:31] [Client thread/INFO]: [CHAT] Scripts reloaded
 
I don't get it. I should work fine. Heres my code for adding a page:
 
mods.thaumcraft.Research.addPage("BLADE", "one.research_page.BLADE");
game.setLocalization("en_US", "one.research_page.BLADE", "burp <BR> Yup, thats how it is");
 
"BLADE" is the key and "one.research_page." is supposed to be page "one".

**Comment by jaredlll08** [comment]
Need the minetweaker.log file. Also gotta warn you, only 1.9/1.10 is really supported, so there wouldn't be a new version, but it may just be a script error :)

**Comment by Shazuli** [comment]
Here is the log file (unfortunately the website doesn't allow txt doucments. So here it is copy-pasted):


INFO: MineTweaker: Building registry
INFO: MineTweaker: Sucessfully built item registry
INFO: Adding command minetweaker
INFO: Adding minetweaker command tooltips
INFO: Adding minetweaker command entities
INFO: Adding minetweaker command research
INFO: Adding minetweaker command aspectList
INFO: Registering Research: BLADE
INFO: Setting localization for the key: tc.research_name.BLADE to Crimson Blade
INFO: Setting localization for the key: tc.research_text.BLADE to Dripping in the enemys blood
INFO: Adding Research Page to BLADE
ERROR: Error executing Thaumcraft.zs: INFUSION_ENCHANTMENT
java.lang.NoSuchFieldError: INFUSION_ENCHANTMENT
	at modtweaker2.mods.thaumcraft.research.AddPage.apply(AddPage.java:79)
	at minetweaker.runtime.MTTweaker.apply(MTTweaker.java:70)
	at minetweaker.MineTweakerAPI.apply(MineTweakerAPI.java:169)
	at modtweaker2.mods.thaumcraft.handlers.Research.addPage(Research.java:100)
	at Thaumcraft.__script__(Thaumcraft.zs:5)
	at __ZenMain__.run(Thaumcraft.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:163)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:656)
	at minetweaker.MineTweakerImplementationAPI.onServerStart(MineTweakerImplementationAPI.java:566)
	at minetweaker.mc18.MineTweakerMod.onServerAboutToStart(MineTweakerMod.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:857)
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:279)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callBoolean(Reflector.java:473)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:203)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
	at java.lang.Thread.run(Unknown Source)
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:1>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:2>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:3>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:4>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:5>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:6>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:7>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:8>
INFO: Adding tooltip for <thaumicbases:ukulele>: minetweaker.mc18.formatting.FormattedMarkupString@3b4383e8
INFO: Adding tooltip for <thaumicbases:ukulele:1>: minetweaker.mc18.formatting.FormattedMarkupString@3a9724b3
INFO: Adding tooltip for <thaumicbases:ukulele:2>: minetweaker.mc18.formatting.FormattedMarkupString@4bf664fe
INFO: Adding tooltip for <thaumicbases:ukulele:3>: minetweaker.mc18.formatting.FormattedMarkupString@5215d84f
INFO: Adding tooltip for <thaumicbases:ukulele:4>: minetweaker.mc18.formatting.FormattedMarkupString@3f2e077a
INFO: Adding tooltip for <thaumicbases:ukulele:5>: minetweaker.mc18.formatting.FormattedMarkupString@343545fb
INFO: Adding tooltip for <thaumicbases:ukulele:6>: minetweaker.mc18.formatting.FormattedMarkupString@6c21249
INFO: Adding tooltip for <thaumicbases:ukulele:7>: minetweaker.mc18.formatting.FormattedMarkupString@21b9c714
INFO: Adding tooltip for <thaumicbases:ukulele:8>: minetweaker.mc18.formatting.FormattedMarkupString@3826eb4a
INFO: Adding minetweaker command tooltips
INFO: Adding minetweaker command entities
INFO: Adding minetweaker command research
INFO: Adding minetweaker command aspectList
INFO: Removing minetweaker command aspectList
INFO: Removing minetweaker command research
INFO: Removing minetweaker command entities
INFO: Removing minetweaker command tooltips
INFO: Removing tooltip for <thaumicbases:ukulele:8>: minetweaker.mc18.formatting.FormattedMarkupString@3826eb4a
INFO: Removing tooltip for <thaumicbases:ukulele:7>: minetweaker.mc18.formatting.FormattedMarkupString@21b9c714
INFO: Removing tooltip for <thaumicbases:ukulele:6>: minetweaker.mc18.formatting.FormattedMarkupString@6c21249
INFO: Removing tooltip for <thaumicbases:ukulele:5>: minetweaker.mc18.formatting.FormattedMarkupString@343545fb
INFO: Removing tooltip for <thaumicbases:ukulele:4>: minetweaker.mc18.formatting.FormattedMarkupString@3f2e077a
INFO: Removing tooltip for <thaumicbases:ukulele:3>: minetweaker.mc18.formatting.FormattedMarkupString@5215d84f
INFO: Removing tooltip for <thaumicbases:ukulele:2>: minetweaker.mc18.formatting.FormattedMarkupString@4bf664fe
INFO: Removing tooltip for <thaumicbases:ukulele:1>: minetweaker.mc18.formatting.FormattedMarkupString@3a9724b3
INFO: Removing tooltip for <thaumicbases:ukulele>: minetweaker.mc18.formatting.FormattedMarkupString@3b4383e8
INFO: [ModTweaker2] Restoring 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:8>
INFO: [ModTweaker2] Restoring 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:7>
INFO: [ModTweaker2] Restoring 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:6>
INFO: [ModTweaker2] Restoring 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:5>
INFO: [ModTweaker2] Restoring 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:4>
INFO: [ModTweaker2] Restoring 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:3>
INFO: [ModTweaker2] Restoring 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:2>
INFO: [ModTweaker2] Restoring 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:1>
INFO: [ModTweaker2] Restoring 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele>
INFO: Setting localization for the key: tc.research_text.BLADE to null
INFO: Setting localization for the key: tc.research_name.BLADE to null
INFO: Removing Research: BLADE
INFO: Removing minetweaker command aspectList
INFO: Removing minetweaker command research
INFO: Removing minetweaker command entities
INFO: Removing minetweaker command tooltips
INFO: Removing command minetweaker
INFO: Adding command minetweaker
INFO: Adding minetweaker command tooltips
INFO: Adding minetweaker command entities
INFO: Adding minetweaker command research
INFO: Adding minetweaker command aspectList
INFO: Registering Research: BLADE
INFO: Setting localization for the key: tc.research_name.BLADE to Crimson Blade
INFO: Setting localization for the key: tc.research_text.BLADE to Dripping in the enemys blood
INFO: Adding Research Page to BLADE
ERROR: Error executing Thaumcraft.zs: INFUSION_ENCHANTMENT
java.lang.NoSuchFieldError: INFUSION_ENCHANTMENT
	at modtweaker2.mods.thaumcraft.research.AddPage.apply(AddPage.java:79)
	at minetweaker.runtime.MTTweaker.apply(MTTweaker.java:70)
	at minetweaker.MineTweakerAPI.apply(MineTweakerAPI.java:169)
	at modtweaker2.mods.thaumcraft.handlers.Research.addPage(Research.java:100)
	at Thaumcraft.__script__(Thaumcraft.zs:5)
	at __ZenMain__.run(Thaumcraft.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:163)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:656)
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:83)
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:642)
	at minetweaker.mc18.server.MCServer$MCCommand.func_71515_b(MCServer.java:147)
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:100)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:79)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:815)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:794)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at net.minecraft.util.Util.func_181617_a(SourceFile:44)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:251)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Unknown Source)
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:1>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:2>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:3>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:4>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:5>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:6>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:7>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:8>
INFO: Adding tooltip for <thaumicbases:ukulele>: minetweaker.mc18.formatting.FormattedMarkupString@77eacc4f
INFO: Adding tooltip for <thaumicbases:ukulele:1>: minetweaker.mc18.formatting.FormattedMarkupString@2d9bf16b
INFO: Adding tooltip for <thaumicbases:ukulele:2>: minetweaker.mc18.formatting.FormattedMarkupString@1563193a
INFO: Adding tooltip for <thaumicbases:ukulele:3>: minetweaker.mc18.formatting.FormattedMarkupString@cbb9dcd
INFO: Adding tooltip for <thaumicbases:ukulele:4>: minetweaker.mc18.formatting.FormattedMarkupString@64294123
INFO: Adding tooltip for <thaumicbases:ukulele:5>: minetweaker.mc18.formatting.FormattedMarkupString@39cfb22
INFO: Adding tooltip for <thaumicbases:ukulele:6>: minetweaker.mc18.formatting.FormattedMarkupString@357b5703
INFO: Adding tooltip for <thaumicbases:ukulele:7>: minetweaker.mc18.formatting.FormattedMarkupString@4851e18b
INFO: Adding tooltip for <thaumicbases:ukulele:8>: minetweaker.mc18.formatting.FormattedMarkupString@15d2f390
INFO: Removing tooltip for <thaumicbases:ukulele:8>: minetweaker.mc18.formatting.FormattedMarkupString@15d2f390
INFO: Removing tooltip for <thaumicbases:ukulele:7>: minetweaker.mc18.formatting.FormattedMarkupString@4851e18b
INFO: Removing tooltip for <thaumicbases:ukulele:6>: minetweaker.mc18.formatting.FormattedMarkupString@357b5703
INFO: Removing tooltip for <thaumicbases:ukulele:5>: minetweaker.mc18.formatting.FormattedMarkupString@39cfb22
INFO: Removing tooltip for <thaumicbases:ukulele:4>: minetweaker.mc18.formatting.FormattedMarkupString@64294123
INFO: Removing tooltip for <thaumicbases:ukulele:3>: minetweaker.mc18.formatting.FormattedMarkupString@cbb9dcd
INFO: Removing tooltip for <thaumicbases:ukulele:2>: minetweaker.mc18.formatting.FormattedMarkupString@1563193a
INFO: Removing tooltip for <thaumicbases:ukulele:1>: minetweaker.mc18.formatting.FormattedMarkupString@2d9bf16b
INFO: Removing tooltip for <thaumicbases:ukulele>: minetweaker.mc18.formatting.FormattedMarkupString@77eacc4f
INFO: [ModTweaker2] Restoring 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:8>
INFO: [ModTweaker2] Restoring 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:7>
INFO: [ModTweaker2] Restoring 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:6>
INFO: [ModTweaker2] Restoring 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:5>
INFO: [ModTweaker2] Restoring 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:4>
INFO: [ModTweaker2] Restoring 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:3>
INFO: [ModTweaker2] Restoring 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:2>
INFO: [ModTweaker2] Restoring 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:1>
INFO: [ModTweaker2] Restoring 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele>
INFO: Setting localization for the key: tc.research_text.BLADE to null
INFO: Setting localization for the key: tc.research_name.BLADE to null
INFO: Removing Research: BLADE
INFO: Removing minetweaker command aspectList
INFO: Removing minetweaker command research
INFO: Removing minetweaker command entities
INFO: Removing minetweaker command tooltips
INFO: Removing command minetweaker
INFO: Adding command minetweaker
INFO: Adding minetweaker command tooltips
INFO: Adding minetweaker command entities
INFO: Adding minetweaker command research
INFO: Adding minetweaker command aspectList
INFO: Registering Research: BLADE
INFO: Setting localization for the key: tc.research_name.BLADE to Crimson Blade
INFO: Setting localization for the key: tc.research_text.BLADE to Dripping in the enemys blood
INFO: Adding Research Page to BLADE
ERROR: Error executing Thaumcraft.zs: INFUSION_ENCHANTMENT
java.lang.NoSuchFieldError: INFUSION_ENCHANTMENT
	at modtweaker2.mods.thaumcraft.research.AddPage.apply(AddPage.java:79)
	at minetweaker.runtime.MTTweaker.apply(MTTweaker.java:70)
	at minetweaker.MineTweakerAPI.apply(MineTweakerAPI.java:169)
	at modtweaker2.mods.thaumcraft.handlers.Research.addPage(Research.java:100)
	at Thaumcraft.__script__(Thaumcraft.zs:5)
	at __ZenMain__.run(Thaumcraft.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:163)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:656)
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:83)
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:642)
	at minetweaker.mc18.server.MCServer$MCCommand.func_71515_b(MCServer.java:147)
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:100)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:79)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:815)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:794)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at net.minecraft.util.Util.func_181617_a(SourceFile:44)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:251)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Unknown Source)
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:1>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:2>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:3>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:4>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:5>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:6>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:7>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:8>
INFO: Adding tooltip for <thaumicbases:ukulele>: minetweaker.mc18.formatting.FormattedMarkupString@292c902c
INFO: Adding tooltip for <thaumicbases:ukulele:1>: minetweaker.mc18.formatting.FormattedMarkupString@531bcbf8
INFO: Adding tooltip for <thaumicbases:ukulele:2>: minetweaker.mc18.formatting.FormattedMarkupString@3089e93f
INFO: Adding tooltip for <thaumicbases:ukulele:3>: minetweaker.mc18.formatting.FormattedMarkupString@6682fea5
INFO: Adding tooltip for <thaumicbases:ukulele:4>: minetweaker.mc18.formatting.FormattedMarkupString@293ed18e
INFO: Adding tooltip for <thaumicbases:ukulele:5>: minetweaker.mc18.formatting.FormattedMarkupString@6e249855
INFO: Adding tooltip for <thaumicbases:ukulele:6>: minetweaker.mc18.formatting.FormattedMarkupString@6fc5d851
INFO: Adding tooltip for <thaumicbases:ukulele:7>: minetweaker.mc18.formatting.FormattedMarkupString@2b93d183
INFO: Adding tooltip for <thaumicbases:ukulele:8>: minetweaker.mc18.formatting.FormattedMarkupString@1c605eba
INFO: Removing tooltip for <thaumicbases:ukulele:8>: minetweaker.mc18.formatting.FormattedMarkupString@1c605eba
INFO: Removing tooltip for <thaumicbases:ukulele:7>: minetweaker.mc18.formatting.FormattedMarkupString@2b93d183
INFO: Removing tooltip for <thaumicbases:ukulele:6>: minetweaker.mc18.formatting.FormattedMarkupString@6fc5d851
INFO: Removing tooltip for <thaumicbases:ukulele:5>: minetweaker.mc18.formatting.FormattedMarkupString@6e249855
INFO: Removing tooltip for <thaumicbases:ukulele:4>: minetweaker.mc18.formatting.FormattedMarkupString@293ed18e
INFO: Removing tooltip for <thaumicbases:ukulele:3>: minetweaker.mc18.formatting.FormattedMarkupString@6682fea5
INFO: Removing tooltip for <thaumicbases:ukulele:2>: minetweaker.mc18.formatting.FormattedMarkupString@3089e93f
INFO: Removing tooltip for <thaumicbases:ukulele:1>: minetweaker.mc18.formatting.FormattedMarkupString@531bcbf8
INFO: Removing tooltip for <thaumicbases:ukulele>: minetweaker.mc18.formatting.FormattedMarkupString@292c902c
INFO: [ModTweaker2] Restoring 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:8>
INFO: [ModTweaker2] Restoring 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:7>
INFO: [ModTweaker2] Restoring 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:6>
INFO: [ModTweaker2] Restoring 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:5>
INFO: [ModTweaker2] Restoring 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:4>
INFO: [ModTweaker2] Restoring 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:3>
INFO: [ModTweaker2] Restoring 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:2>
INFO: [ModTweaker2] Restoring 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:1>
INFO: [ModTweaker2] Restoring 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele>
INFO: Setting localization for the key: tc.research_text.BLADE to null
INFO: Setting localization for the key: tc.research_name.BLADE to null
INFO: Removing Research: BLADE
INFO: Removing minetweaker command aspectList
INFO: Removing minetweaker command research
INFO: Removing minetweaker command entities
INFO: Removing minetweaker command tooltips
INFO: Removing command minetweaker
INFO: Adding command minetweaker
INFO: Adding minetweaker command tooltips
INFO: Adding minetweaker command entities
INFO: Adding minetweaker command research
INFO: Adding minetweaker command aspectList
INFO: Registering Research: BLADE
INFO: Setting localization for the key: tc.research_name.BLADE to Crimson Blade
INFO: Setting localization for the key: tc.research_text.BLADE to Dripping in the enemys blood
INFO: Adding Research Page to BLADE
ERROR: Error executing Thaumcraft.zs: INFUSION_ENCHANTMENT
java.lang.NoSuchFieldError: INFUSION_ENCHANTMENT
	at modtweaker2.mods.thaumcraft.research.AddPage.apply(AddPage.java:79)
	at minetweaker.runtime.MTTweaker.apply(MTTweaker.java:70)
	at minetweaker.MineTweakerAPI.apply(MineTweakerAPI.java:169)
	at modtweaker2.mods.thaumcraft.handlers.Research.addPage(Research.java:100)
	at Thaumcraft.__script__(Thaumcraft.zs:5)
	at __ZenMain__.run(Thaumcraft.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:163)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:656)
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:83)
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:642)
	at minetweaker.mc18.server.MCServer$MCCommand.func_71515_b(MCServer.java:147)
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:100)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:79)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:815)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:794)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at net.minecraft.util.Util.func_181617_a(SourceFile:44)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:251)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Unknown Source)
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:1>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:2>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:3>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:4>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:5>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:6>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:7>
INFO: [ModTweaker2] Removing 1 Thaumcraft Infusion Recipe(s) for <thaumicbases:ukulele:8>
INFO: Adding tooltip for <thaumicbases:ukulele>: minetweaker.mc18.formatting.FormattedMarkupString@76645a32
INFO: Adding tooltip for <thaumicbases:ukulele:1>: minetweaker.mc18.formatting.FormattedMarkupString@5636e18d
INFO: Adding tooltip for <thaumicbases:ukulele:2>: minetweaker.mc18.formatting.FormattedMarkupString@34dc8c43
INFO: Adding tooltip for <thaumicbases:ukulele:3>: minetweaker.mc18.formatting.FormattedMarkupString@b488ccd
INFO: Adding tooltip for <thaumicbases:ukulele:4>: minetweaker.mc18.formatting.FormattedMarkupString@54e9e840
INFO: Adding tooltip for <thaumicbases:ukulele:5>: minetweaker.mc18.formatting.FormattedMarkupString@687c51f6
INFO: Adding tooltip for <thaumicbases:ukulele:6>: minetweaker.mc18.formatting.FormattedMarkupString@4961f866
INFO: Adding tooltip for <thaumicbases:ukulele:7>: minetweaker.mc18.formatting.FormattedMarkupString@8b7e8c7
INFO: Adding tooltip for <thaumicbases:ukulele:8>: minetweaker.mc18.formatting.FormattedMarkupString@1151558c

**Comment by jaredlll08** [comment]
huh, this is really weird iirc I build this based on 5.2.4, can you try downgrade TC and see if it works?

**Comment by Shazuli** [comment]
I downgraded TC to version 5.1.6, now it works. I assume it has something to do with the new "Infusion Enchantments" research. But I rather not downgrade to 5.1.6, the newest (5.2.4) has alot of bug fixes and even more features.

**Comment by jaredlll08** [comment]
ok well, like I said we are not updating 1.8.9 anymore sorry :/
