### ISSUE TITLE
[1.10.2] Squeezer recipe removal error

### ISSUE THREAD

**Issue by The-Arcanian** [jaredlll08/ModTweaker#343]
Using:
mods.forestry.Squeezer.removeRecipe(<liquid:juice>, [<minecraft:apple>]);
causes:
ERROR: Error executing forestry.zs: minetweaker/mc19/liquid/MCLiquidStack
java.lang.NoClassDefFoundError: minetweaker/mc19/liquid/MCLiquidStack
	at modtweaker2.helpers.InputHelper.toILiquidStack(InputHelper.java:100)
	at modtweaker2.mods.forestry.handlers.Squeezer.removeRecipe(Squeezer.java:88)
	at Forestry.__script__(forestry.zs:5)
	at __ZenMain__.run(forestry.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:161)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:682)
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:75)
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:667)
	at minetweaker.mc1102.server.MCServer$MCCommand.func_184881_a(MCServer.java:122)
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:103)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:82)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892)
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.util.Util.func_181617_a(SourceFile:45)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jaredlll08** [comment]
known error, already fixed.
