### ISSUE TITLE
ModTweaker breaking search rules for help list

### ISSUE THREAD

**Issue by TheDarkFlame** [jaredlll08/ModTweaker#346]
Edit: Using Java 8 x64, running minecraft 1.10.2 with forge 12.18.1.2073 (latest)

Upon typing the /help command on a dedicated server, the following output is obtained:

`[23:09:29] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: An unknown error occurred while attempting to perform this command
[23:09:29] [Server thread/WARN] [net.minecraft.command.CommandHandler]: Couldn't process command: 'help'
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:866) ~[?:1.8.0_91]
	at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:483) ~[?:1.8.0_91]
	at java.util.ComparableTimSort.mergeForceCollapse(ComparableTimSort.java:422) ~[?:1.8.0_91]
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:222) ~[?:1.8.0_91]
	at java.util.Arrays.sort(Arrays.java:1312) ~[?:1.8.0_91]
	at java.util.Arrays.sort(Arrays.java:1506) ~[?:1.8.0_91]
	at java.util.ArrayList.sort(ArrayList.java:1454) ~[?:1.8.0_91]
	at java.util.Collections.sort(Collections.java:141) ~[?:1.8.0_91]
	at net.minecraft.command.CommandHelp.func_184900_a(SourceFile:118) ~[al.class:?]
	at net.minecraft.command.CommandHelp.func_184881_a(SourceFile:73) ~[al.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:104) [k.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:83) [k.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:423) [ld.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:388) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]`

upon using https://minecraft.curseforge.com/projects/helpfixer the issue was reported to be that of MineTweaker. But disabling ModTweaker (and helpfixer, as it both reports on and fixes the issue) removes the error that is being reported.
HelpFixer reports the following 2 lines:
`[23:22:00] [Server thread/WARN] [com.matthewprenger.helpfixer.HelpFixer]: Command [minetweaker, minetweaker.mc1102.server.MCServer$MCCommand] incorrectly overrides compareTo: %s
[23:22:00] [Server thread/WARN] [com.matthewprenger.helpfixer.HelpFixer]: Command [minetweaker, minetweaker.mc1102.server.MCServer$MCCommand] incorrectly overrides compareTo: %s`

let me know if I need to contribute anything else to help.

**Comment by jaredlll08** [comment]
This is a crafttweaker issue, mind posting it there please :)
