### ISSUE TITLE
Botania support

### ISSUE THREAD

**Issue by mightydanp** [jaredlll08/ModTweaker#357]
It appears that botania needs support. Right now the imports do not work

**Comment by Yulife** [comment]
For 1.10?

**Comment by mightydanp** [comment]
yes

**Comment by Yulife** [comment]
It'd really help if you posted more than just " doesn't work".

**Comment by mightydanp** [comment]
ok thanks but version i am using is1.10 and the imports wont import botania

ERROR: Botania.zs:9 > No such member: botania
ERROR: Botania.zs:10 > No such member: botania
ERROR: Error executing Botania.zs: 2
java.lang.ArrayIndexOutOfBoundsException: 2
	at stanhebben.zenscript.type.natives.JavaMethod.rematch(JavaMethod.java:153)
	at stanhebben.zenscript.expression.ExpressionCallVirtual.<init>(ExpressionCallVirtual.java:37)
	at stanhebben.zenscript.type.ZenTypeAny.call(ZenTypeAny.java:202)
	at stanhebben.zenscript.expression.Expression.call(Expression.java:81)
	at stanhebben.zenscript.parser.expression.ParsedExpressionCall.compile(ParsedExpressionCall.java:42)
	at stanhebben.zenscript.statements.StatementExpression.compile(StatementExpression.java:19)
	at stanhebben.zenscript.ZenModule.compileScripts(ZenModule.java:111)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:157)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:682)
	at minetweaker.MineTweakerImplementationAPI.onServerStart(MineTweakerImplementationAPI.java:591)
	at minetweaker.mc1102.MineTweakerMod.onServerStarting(MineTweakerMod.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:595)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
	at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:838)
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:292)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:122)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mightydanp** [comment]
import mods.botania.ManaInfusion;

mods.botania.ManaInfusion.removeRecipe(<botania:manaResource>);
mods.botania.ManaInfusion.addInfusion(<botania:manaResource>, steel, 1000);

**Comment by jaredlll08** [comment]
What version of modtweaker?

**Comment by mightydanp** [comment]
The latest version

**Comment by jaredlll08** [comment]
No. if you continue to give me minimal info, then I will start to give this minimal attention.
Give me the exact version number of modtweaker, exact version number of crafttweaker, the WHOLE minetweaker.log file, uploaded to pastebin or similar, ALL of your scripts, once again, Pastebin or similar.

**Comment by mightydanp** [comment]
Botania-unofficial.r1.8-321
CraftTweaker-1.10.2-3.0.11
ModTweaker2-2.0.2

botania http://pastebin.com/URBWXhih
compact solars http://pastebin.com/56zx6Qnn
Ender IO http://pastebin.com/hBpzGXiE
ExtreameReactors http://pastebin.com/fjCd0tnB

Minetweak log: http://pastebin.com/nmSQ5HxP
i know that the gregtech one doesnt work.

**Comment by mightydanp** [comment]
I just downloaded the src and did a build of this change and i get this

INFO: MineTweaker: Building registry
INFO: MineTweaker: Sucessfully built item registry
INFO: Adding command minetweaker
INFO: Adding minetweaker command tooltips
INFO: 
INFO: Adding minetweaker command randomthings
INFO: Adding minetweaker command materials
INFO: Adding minetweaker command modifiers
INFO: Adding minetweaker command tconstruct
ERROR: ?:1 > No such member: botania
ERROR: ?:1 > Not a valid type
ERROR: Botania.zs:9 > No such member: botania
ERROR: Botania.zs:10 > No such member: botania
ERROR: Error executing Botania.zs: 2
java.lang.ArrayIndexOutOfBoundsException: 2
at stanhebben.zenscript.type.natives.JavaMethod.rematch(JavaMethod.java:153)
at stanhebben.zenscript.expression.ExpressionCallVirtual.(ExpressionCallVirtual.java:37)
at stanhebben.zenscript.type.ZenTypeAny.call(ZenTypeAny.java:202)
at stanhebben.zenscript.expression.Expression.call(Expression.java:81)
at stanhebben.zenscript.parser.expression.ParsedExpressionCall.compile(ParsedExpressionCall.java:42)
at stanhebben.zenscript.statements.StatementExpression.compile(StatementExpression.java:19)
at stanhebben.zenscript.ZenModule.compileScripts(ZenModule.java:111)
at minetweaker.runtime.MTTweaker.load(MTTweaker.java:157)
at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:682)
at minetweaker.MineTweakerImplementationAPI.onServerStart(MineTweakerImplementationAPI.java:591)
at minetweaker.mc1102.MineTweakerMod.onServerStarting(MineTweakerMod.java:160)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:597)
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:840)
at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:292)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at Reflector.callBoolean(Reflector.java:523)
at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:205)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
at java.lang.Thread.run(Thread.java:745)
INFO: Removing 1 recipes
INFO: Adding recipe for Low Voltage Solar Array
ERROR: ?:2 > No such member: nei
ERROR: ?:2 > Not a valid type
ERROR: Ender IO.zs:3 > No such member: gregtech
ERROR: Ender IO.zs:3 > Not a valid type
INFO: Removing 4 furnace recipes
INFO: Removing Silicon from ore dictionary entry itemSilicon
INFO: Removing 1 recipes
INFO: Adding recipe for Insulated Redstone Conduit
INFO: Removing 0 recipes
INFO: Adding recipe for Insulated Redstone Conduit
INFO: Removing 1 recipes
INFO: Adding recipe for Network Conduit (OC)
INFO: Removing 1 recipes
INFO: Adding recipe for Basic Gear
INFO: Removing 1 recipes
INFO: Adding recipe for Machine Chassis
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 2 recipes
INFO: Removing 2 recipes
INFO: Removing 1 recipes
INFO: Removing 2 recipes
INFO: Removing 2 recipes
INFO: Removing 1 recipes
INFO: Removing 0 recipes
INFO: Adding recipe for Red Alloy Ingot
INFO: Removing 3 furnace recipes
INFO: Removing 2 recipes
INFO: Turbine Housing Core
INFO: Removing 1 recipes
INFO: Adding recipe for Turbine Housing Core (Legacy)
INFO: Turbine Housing
INFO: Removing 1 recipes
INFO: Adding recipe for Turbine Housing (Legacy)
INFO: Turbine Glass
INFO: Removing 1 recipes
INFO: Adding recipe for Turbine Glass (Legacy)
INFO: Reactor Housing Core
INFO: Removing 1 recipes
INFO: Adding recipe for Reactor Casing Core (Legacy)
INFO: Reactor Housing
INFO: Removing 1 recipes
INFO: Adding recipe for Reactor Casing (Legacy)
INFO: Reactor Glass
INFO: Removing 1 recipes
INFO: Adding recipe for Reactor Glass (Legacy)
INFO: Fuel Rod
INFO: Removing 1 recipes
INFO: Adding recipe for Reactor Fuel Rod (Legacy)
INFO: Turbine Rotor Shaft
INFO: Removing 1 recipes
INFO: Adding recipe for Turbine Rotor Shaft (Legacy)
INFO: Turbine Rotor Blade
INFO: Removing 1 recipes
INFO: Adding recipe for Turbine Rotor Blade (Legacy)
INFO: Extreme Wrench
INFO: Removing 1 recipes
INFO: Adding recipe for Extreme Wrench
INFO: 
INFO: 
INFO: 
INFO: 
INFO: 
INFO: 
INFO: tried to remove command: tconstruct failed. THIS IS NOT AN ERROR!
INFO: tried to remove command: modifiers failed. THIS IS NOT AN ERROR!
INFO: tried to remove command: materials failed. THIS IS NOT AN ERROR!
INFO: tried to remove command: randomthings failed. THIS IS NOT AN ERROR!
INFO: tried to remove command: entities failed. THIS IS NOT AN ERROR!
INFO: tried to remove command: tooltips failed. THIS IS NOT AN ERROR!
INFO: Removing recipe for Extreme Wrench
INFO: Restoring 1 recipes
INFO: Removing recipe for Turbine Rotor Blade (Legacy)
INFO: Restoring 1 recipes
INFO: Removing recipe for Turbine Rotor Shaft (Legacy)
INFO: Restoring 1 recipes
INFO: Removing recipe for Reactor Fuel Rod (Legacy)
INFO: Restoring 1 recipes
INFO: Removing recipe for Reactor Glass (Legacy)
INFO: Restoring 1 recipes
INFO: Removing recipe for Reactor Casing (Legacy)
INFO: Restoring 1 recipes
INFO: Removing recipe for Reactor Casing Core (Legacy)
INFO: Restoring 1 recipes
INFO: Removing recipe for Turbine Glass (Legacy)
INFO: Restoring 1 recipes
INFO: Removing recipe for Turbine Housing (Legacy)
INFO: Restoring 1 recipes
INFO: Removing recipe for Turbine Housing Core (Legacy)
INFO: Restoring 1 recipes
INFO: Restoring 2 recipes
INFO: Restoring 3 furnace recipes
INFO: Removing recipe for Red Alloy Ingot
INFO: Restoring 0 recipes
INFO: Restoring 1 recipes
INFO: Restoring 2 recipes
INFO: Restoring 2 recipes
INFO: Restoring 1 recipes
INFO: Restoring 2 recipes
INFO: Restoring 2 recipes
INFO: Restoring 1 recipes
INFO: Restoring 1 recipes
INFO: Restoring 1 recipes
INFO: Removing recipe for Machine Chassis
INFO: Restoring 1 recipes
INFO: Removing recipe for Basic Gear
INFO: Restoring 1 recipes
INFO: Removing recipe for Network Conduit (OC)
INFO: Restoring 1 recipes
INFO: Removing recipe for Insulated Redstone Conduit
INFO: Restoring 0 recipes
INFO: Removing recipe for Insulated Redstone Conduit
INFO: Restoring 1 recipes
INFO: Restoring Silicon to ore dictionary entry itemSilicon
INFO: Restoring 4 furnace recipes
INFO: Removing recipe for Low Voltage Solar Array
INFO: Restoring 1 recipes
INFO: tried to remove command: tconstruct failed. THIS IS NOT AN ERROR!
INFO: tried to remove command: modifiers failed. THIS IS NOT AN ERROR!
INFO: tried to remove command: materials failed. THIS IS NOT AN ERROR!
INFO: tried to remove command: randomthings failed. THIS IS NOT AN ERROR!
INFO: tried to remove command: entities failed. THIS IS NOT AN ERROR!
INFO: tried to remove command: tooltips failed. THIS IS NOT AN ERROR!
INFO: tried to remove command: minetweaker failed. THIS IS NOT AN ERROR!
INFO: 
INFO: 
INFO: 
INFO: 
INFO: 
INFO:
@mightydanp
mightydanp 
commented about 9 hours ago
commented on 2a9a867
import mods.botania.ManaInfusion;

val steel = ore:ingotSteel;
val mana = ore:ingotManaSteel;
val manasteel = botania:manaResource;
val blocksteel = ore:blockSteel;

// botania Nerf
mods.botania.ManaInfusion.removeRecipe(botania:manaResource);
mods.botania.ManaInfusion.addInfusion(botania:manaResource, steel, 1000);

mods.botania.ManaInfusion.removeRecipe(botania:storage);
mods.botania.ManaInfusion.addInfusion(botania:storage, blocksteel, 5000);

**Comment by Sunconure11** [comment]
Is this issue still a thing on 1.11.2? I'm running into it.
