### ISSUE TITLE
on running 'minetweaker tconstruct' or 'minetweaker tconstruct Casting', etc.

### ISSUE THREAD

**Issue by morninggloree** [jaredlll08/ModTweaker#365]
[22:22:32] [Client thread/INFO]: [CHAT] Invalid arguments for command. Valid arguments: Casting, Drying, Smeltery

[22:22:40] [Server thread/WARN]: Couldn't process command: 'minetweaker tconstruct'
java.lang.NoClassDefFoundError: slimeknights/tconstruct/library/smeltery/ICastingRecipe
	at modtweaker.mods.tconstruct.commands.TConstructLogger.execute(TConstructLogger.java:39) ~[TConstructLogger.class:?]
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:667) ~[MineTweakerImplementationAPI$19.class:?]
	at minetweaker.mc1102.server.MCServer$MCCommand.func_184881_a(MCServer.java:122) ~[MCServer$MCCommand.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:104) [k.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:83) [k.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) [me.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) [me.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [im.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [im.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.ClassNotFoundException: slimeknights.tconstruct.library.smeltery.ICastingRecipe
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	... 18 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	... 18 more
[22:22:40] [Client thread/INFO]: [CHAT] An unknown error occurred while attempting to perform this command

only mods loaded are latest Curse-releases (as of 2016-09-21) of Tinkers, CraftTweaker & ModTweaker, in 1.10.2, forge 12.18.1.2093

**Comment by jdratlif** [comment]
I'm getting the same error on ModTweaker 2.0.5 with MineTweaker 3 (Craft Tweaker) 3.0.13.

**Comment by jaredlll08** [comment]
Fixed in latest commit.
