### ISSUE TITLE
Random server crash

### ISSUE THREAD

**Issue by Cuppycake** [jaredlll08/ModTweaker#397]
http://pastebin.com/Zbf41etS

Haven't seen a pattern or specific event triggering the crashes.

**Comment by jaredlll08** [comment]
May I ask what leads you to believe that this is a modtweaker crash?

**Comment by Lanse505** [comment]
1. Doesn't mention Modtweaker anywhere in the stacktrace outside of it being loaded

2. However it does mention
```
    at com.nguyenquyhy.discordbridge.logics.LoginHandler.loginBotAccount(LoginHandler.java:55)
    at com.nguyenquyhy.discordbridge.DiscordBridge.onServerStart(DiscordBridge.java:70)
    at org.spongepowered.common.event.listener.GameStartedServerEventListener_DiscordBridge_onServerStart16.handle(Unknown Source)
    at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:301)
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:330)
    at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:229)
```

So SpongeDiscord might be the culprit?

**Comment by Cuppycake** [comment]
Sorry on my phone at work I think I grabbed the wrong one.  We are having a few different crashes and of course now I can't find it lol.  Sorry for the time if I find it again later at home I'll shoot it over

**Comment by jaredlll08** [comment]
Well regardless, modtweaker doesn't do anything during runtime, unless /mt
reload is called, so unless the crash happens on client joining, command
ran or server start, it is not us.

**Comment by jaredlll08** [comment]
Since this isn't our crash, I'm closing it
