### ISSUE TITLE
"cannot apply actions" when using chisel.Carving.removeGroup

### ISSUE THREAD

**Issue by Efimero** [jaredlll08/ModTweaker#615]
#### Issue Description:
using `mod.chisel.Carving.removeGroup()` causes the script to fail

#### What happens:
```
[AVAILABLE][CLIENT][INFO] Removing chisel group called: blockGold
[AVAILABLE][CLIENT][ERROR] Error while applying actions
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1476)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1474)
	at com.google.common.collect.AbstractMapBasedMultimap$AsMap$AsMapIterator.next(AbstractMapBasedMultimap.java:1428)
	at com.google.common.collect.AbstractMapBasedMultimap$AsMap$AsMapIterator.next(AbstractMapBasedMultimap.java:1417)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at team.chisel.common.carving.Carving.removeGroup(Carving.java:198)
	at com.blamejared.compat.chisel.Carving$ActionRemoveGroup.apply(Carving.java:104)
	at crafttweaker.runtime.CrTTweaker.apply(CrTTweaker.java:53)
	etc...
```

#### What you expected to happen:
removing the group and reading the rest of the script =)

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://gist.github.com/Efimero/bc47507a38cd5fa3ee47511e01ad44f2

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://gist.github.com/Efimero/a21ba7f15964249e2e835b52149a1148

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 2611
- Crafttweaker: 4.1.6
- ModTweaker: 4.0.8
- MTLib: 3.0.4

**Comment by jaredlll08** [comment]
Chisel issue.
