### ISSUE TITLE
Actually Additions support

### ISSUE THREAD

**Issue by PanSzelescik** [jaredlll08/ModTweaker#652]
https://github.com/Ellpeck/ActuallyAdditions/issues/1126

**Comment by rallias** [comment]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mod Tweaker (modtweaker)
Caused by: java.lang.IllegalAccessError: tried to access field de.ellpeck.actuallyadditions.api.recipe.EmpowererRecipe.output from class com.blamejared.compat.actuallyaddition.Empowerer$Add
	at com.blamejared.compat.actuallyaddition.Empowerer$Add.getRecipeInfo(Empowerer.java:46)
	at com.blamejared.compat.actuallyaddition.Empowerer$Add.getRecipeInfo(Empowerer.java:38)
	at com.blamejared.mtlib.utils.BaseListModification.getRecipeInfo(BaseListModification.java:24)
	at com.blamejared.mtlib.utils.BaseListAddition.describe(BaseListAddition.java:42)
	at crafttweaker.runtime.CrTTweaker.apply(CrTTweaker.java:49)
	at crafttweaker.CraftTweakerAPI.apply(CraftTweakerAPI.java:135)
	at java.lang.Iterable.forEach(Unknown Source)
	at com.blamejared.ModTweaker.loadComplete(ModTweaker.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:752)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:329)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

https://github.com/jaredlll08/ModTweaker/blob/1.12/src/main/java/com/blamejared/compat/actuallyaddition/Empowerer.java#L46

https://github.com/Ellpeck/ActuallyAdditions/commit/5c149648da131be150ae42942352e4a7a2fecae7#diff-eaee1f7d5b39659ac457808d9cc5ffccL17

Actually Additions broke backwards compatibility.

**Comment by Darkhax** [comment]
Yep, Shadows broke your compat. Also, what's up with your package name `com.blamejared.compat` lol

**Comment by MasterEnderman** [comment]
Got another Crash Report: https://paste.dimdev.org/aqehituzes.mccrash

**Comment by Koennn** [comment]
This is due to a change in the latest version of ActuallyAdditions, several deprecated fields have been removed, see [this diff](https://github.com/Ellpeck/ActuallyAdditions/commit/5c149648da131be150ae42942352e4a7a2fecae7#diff-9f79941a8d193730581f98995198bf66)

**Comment by Darkhax** [comment]
Jared's gone on vacation, so just use the old version for now.

**Comment by TheSnowyChickens** [comment]
Is this the same crash? https://paste.dimdev.org/uvuqadivuv.mccrash

**Comment by Darkhax** [comment]
Yes it is @TheSnowyChickens

**Comment by jaredlll08** [comment]
fixed

**Comment by TheSnowyChickens** [comment]
Juhuu
