### ISSUE TITLE
[Extra Utilities] Resonator.remove() broken with latest ExU2 release

### ISSUE THREAD

**Issue by luke-bravenboer** [jaredlll08/ModTweaker#683]
With the recent release of Extra Utilities version 1.12-1.9.2, my crafttweaker scripts are causing the game to crash on startup with the following exception:

```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mod Tweaker (modtweaker)
Caused by: java.lang.NoClassDefFoundError: com/rwtema/extrautils2/tile/TileResonator$ResonatorRecipe
    at com.blamejared.compat.extrautils2.Resonator$Remove.apply(Resonator.java:76)
    at crafttweaker.runtime.CrTTweaker.apply(CrTTweaker.java:53)
    at crafttweaker.CraftTweakerAPI.apply(CraftTweakerAPI.java:135)
    at com.blamejared.ModTweaker$$Lambda$2908/1413539394.accept(Unknown Source)
```
(Full crash log: https://paste.dimdev.org/ocayofeduk.mccrash)

Seems like rwtema's changed something about the Resonator recipes.

This line in my script's the culprit (commenting it out prevents the crash):
`Resonator.remove(<extrautils2:ingredients:13>);`

Interestingly, I've got some '`Resonator.add()`' lines in my script too, which are indeed still working fine- it's actually only the .remove() method that's affected.
(The ExU Crusher wasn't affected.)

#### Versions:
CraftTweaker: 1.12-4.1.9
ModTweaker: 4.0.13
Extra Utilities 2: 1.12-1.9.2
Forge: 2738

**Comment by ToMe25** [comment]
for me it says:
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mod Tweaker (modtweaker)
Caused by: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: com/rwtema/extrautils2/tile/TileResonator$ResonatorRecipe
	at com.blamejared.compat.extrautils2.Resonator$Remove.apply(Resonator.java:76)
	at crafttweaker.runtime.CrTTweaker.apply(CrTTweaker.java:51)
	at crafttweaker.CraftTweakerAPI.apply(CraftTweakerAPI.java:135)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.blamejared.ModTweaker.loadComplete(ModTweaker.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:752)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: com/rwtema/extrautils2/tile/TileResonator$ResonatorRecipe
	... 45 more
Caused by: java.lang.ClassNotFoundException: com.rwtema.extrautils2.tile.TileResonator$ResonatorRecipe
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 45 more
Caused by: java.lang.NullPointerException
```
but it also Crashes.

**Comment by jaredlll08** [comment]
I can't reproduce.

**Comment by ToMe25** [comment]
@jaredlll08 have you Tried it with the newest public release?

**Comment by ToMe25** [comment]
of both Mods?

**Comment by jaredlll08** [comment]
I tried it in my dev environment, so yes to the modtweaker version, and the
latest public stable release from curseforge for extra util.

Try without vanillafix and get back to me.

**Comment by ToMe25** [comment]
I never used VanillaFix.

**Comment by ToMe25** [comment]
Try it outside of a Dev Enviroment sometimes that changes something.

**Comment by ToMe25** [comment]
@jaredlll08 this error occures because XU2-1.9.2 has moved Resonator Recipes to a own Class.

**Comment by ToMe25** [comment]
Thanks :)
