### ISSUE TITLE
Calling /ct ticmat throw error when Laser Gun disabled

### ISSUE THREAD

**Issue by Krutoy242** [jaredlll08/ModTweaker#752]
#### What happens:
I disabled Laser Gun in PlusTic (7.1.6.1) config `plustic.cfg`
```cs
    # Enable Laser Gun [default: true]
    B:"Enable Laser Gun"=false
```
Calling command /ct ticmat now throw an error.
I using [Enigmatica 2 expert](https://www.curseforge.com/minecraft/modpacks/enigmatica2expert) modpack (with additional mods), and can't replicate this error on fresh client with only CT+Plustic installed

#### Error
```c
> /ct ticmat
[21:05:28] [Server thread/INFO] [minecraft/DedicatedServer]: An unknown error occurred while attempting to perform this command
[21:05:28] [Server thread/WARN] [minecraft/CommandHandler]: Couldn't process command: ct ticmat
java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at landmaster.plustic.tools.stats.BatteryCellMaterialStats.getLocalizedInfo(BatteryCellMaterialStats.java:26) ~[BatteryCellMaterialStats.class:?]
        at com.blamejared.compat.tconstruct.TConstruct$1.executeCommand(TConstruct.java:29) ~[TConstruct$1.class:?]
        at crafttweaker.mc1120.commands.CTChatCommand.func_184881_a(CTChatCommand.java:75) ~[CTChatCommand.class:?]
        at com.feed_the_beast.ftbutilities.ranks.CommandOverride.func_184881_a(CommandOverride.java:83) ~[CommandOverride.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
        [...]
```

____
#### Affected Versions:

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Crafttweaker: 4.1.19
- ModTweaker: 4.0.18
- MTLib: 3.0.6

#### Your most recent log file where the issue was present: 

[latest.log](https://gist.github.com/Krutoy242/2865a10d94eeeffbc0f3cd17520ffadc)

**Comment by jaredlll08** [comment]
not my issue, complain to plustic
