### ISSUE TITLE
infusion thaumcraft

### ISSUE THREAD

**Issue by DmitrijevK** [jaredlll08/ModTweaker#765]
#### What you expected to happen:
Hello! I am trying to create infusion recipe (Thaumcraft 6).
But how i can change amount of aspects?

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://gist.github.com/Dmitrjiev/9a0026897dfda2dac7dd1747fe5738ce

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
[PREINITIALIZATION][CLIENT][INFO] Thank you to the Patreon supporters below and others who make CraftTweaker possible!
realTIMematrix
Jonathan McManus
Robijnvogel
Peregrinus11
quaternary
otakup0pe
NickT
IDroid
AdaraChristine
DreamThorn
Pongo Sapiens
If you want to support the mod, checkout https://patreon.com/jaredlll08?s=crtmod

[PREINITIALIZATION][CLIENT][INFO] Current loaders after merging: [[preinit]]
[PREINITIALIZATION][CLIENT][INFO] Loading scripts for loader with names [preinit]
[PREINITIALIZATION][CLIENT][INFO] [preinit | SIDE_CLIENT]: Skipping file {[0:crafttweaker]: infusion.zs} as we are currently loading with a different loader
[PREINITIALIZATION][CLIENT][INFO] Completed script loading in: 2ms
[INITIALIZATION][CLIENT][INFO] CraftTweaker: Building registry
[INITIALIZATION][CLIENT][INFO] CraftTweaker: Successfully built item registry
[INITIALIZATION][CLIENT][INFO] Current loaders after merging: [[preinit], [recipeevent | crafttweaker]]
[INITIALIZATION][CLIENT][INFO] Loading scripts for loader with names [crafttweaker | recipeevent]
[INITIALIZATION][CLIENT][INFO] [crafttweaker | SIDE_CLIENT]: Loading Script: {[0:crafttweaker]: infusion.zs}
[INITIALIZATION][CLIENT][ERROR] infusion.zs:3: Could not resolve <aspect : aer * 20>
[INITIALIZATION][CLIENT][ERROR] infusion.zs:3: Could not resolve <aspect : ignis * 30>
[INITIALIZATION][CLIENT][ERROR] [crafttweaker]: Error executing {[0:crafttweaker]: infusion.zs}: null
java.lang.NullPointerException
	at com.blamejared.compat.thaumcraft.handlers.ThaumCraft.getAspect(ThaumCraft.java:80)
	at com.blamejared.compat.thaumcraft.handlers.ThaumCraft.getAspects(ThaumCraft.java:86)
	at com.blamejared.compat.thaumcraft.handlers.handlers.Infusion.registerRecipe(Infusion.java:26)
	at Infusion.__script__(infusion.zs:3)
	at __ZenMain__.run(Infusion)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:225)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:105)
	at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:73)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_878_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3931)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[INITIALIZATION][CLIENT][INFO] Completed script loading in: 275ms
[POSTINITIALIZATION][CLIENT][INFO] Removing recipes for various outputs
[AVAILABLE][CLIENT][INFO] Fixed the RecipeBook

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- Crafttweaker:  2-1.12-4.1.20.586
- ModTweaker: 4.0.18
- MTLib: 3.0

#### Your most recent log file where the issue was present: 

https://gist.github.com/Dmitrjiev/fb059f5107ce24d71ceafa1d8ea6c9fb

**Comment by jaredlll08** [comment]
follow the issue template and put your scripts on pastebin or gist.github.com.

**Comment by DmitrijevK** [comment]
https://gist.github.com/Dmitrjiev/9a0026897dfda2dac7dd1747fe5738ce
https://gist.github.com/Dmitrjiev/fb059f5107ce24d71ceafa1d8ea6c9fb

**Comment by jaredlll08** [comment]
```
<aspect:aer> * 20
```
