### ISSUE TITLE
https://github.com/jaredlll08/ModTweaker/commit/3213f31f3d178c33154b5a5f52288c6ab668986e breaks mods.betterwithmods.Mill.addRecipe(IIngredient[] inputs, IItemStack[] outputs);

### ISSUE THREAD

**Issue by wormzjl** [jaredlll08/ModTweaker#780]
modtweaker-4.0.19
Old script gives this error:
```
[INITIALIZATION][CLIENT][ERROR] [crafttweaker]: Error executing {[100:crafttweaker]: recipes_base\betterwithmods.zs}: betterwithmods.common.registry.bulk.recipes.MillRecipe.setTicks(I)Lbetterwithmods/common/registry/bulk/recipes/MillRecipe;
java.lang.NoSuchMethodError: betterwithmods.common.registry.bulk.recipes.MillRecipe.setTicks(I)Lbetterwithmods/common/registry/bulk/recipes/MillRecipe;
	at com.blamejared.compat.betterwithmods.base.bulkrecipes.MillBuilder.build(MillBuilder.java:23)
	at com.blamejared.compat.betterwithmods.Mill.addRecipe(Mill.java:28)
	at recipes_base\Betterwithmods.__script__(recipes_base\betterwithmods.zs:24)
	at __ZenMain__.run(recipes_base\Betterwithmods)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:240)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:105)
	at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:67)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_906_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3931)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by jaredlll08** [comment]
@democat3457 any ideas?

**Comment by democat3457** [comment]
@wormzjl whats your bwm version

**Comment by democat3457** [comment]
welp since theres no activity ill just say this:

this crash is caused by an outdated bwm version, upgrade to 2.3.24
